### ISSUE TITLE
Add support to CH180WIFI model

### ISSUE THREAD

**Issue by IvanMazzoli** [ruizmarc/homebridge-intelliclima#1]
**Is your feature request related to a problem? Please describe:**
Right now, the plugin only supports the C800WiFi model. I would love to have support for the CH180WIFI model(s) that I have.

**Describe the solution you'd like:**
More or less what the plugin does with the C800WiFi model, but for the CH180WIFI 

**Describe alternatives you've considered:**
This, as far as I know, it's the only project that supports communication with the Intelliclima API. No real alternatives.

**Additional context:**
Obviously, I'm willing to help and debug to bring this feature to the project!

**Comment by ruizmarc** [comment]
Hi!

Happy to help 😄 As there is no official documentation for this, I would need to observe how the App communicates with the API to be able to reproduce that behavior in the plugin.

I think the most effective way of doing it, it is to have access to an account with an online device like yours. That would require that you prepare an account for me with your thermostat or just temporary share with me your account credentials. Once we get it working, you could change your password for your privacy. As it is something private, I suggest you to look for me on homebridge discord and send me a PM

https://discord.gg/homebridge-432663330281226270

**Comment by IvanMazzoli** [comment]
I agree with you, giving the credentials to the app would be the easiest thing to do, but unfortunately I can't really share them.
There's no other way around it? Like setting a MITM proxy?

**Comment by ruizmarc** [comment]
In that case, I would need that you provide all requests and responses sent and received by the app including headers and which action you were doing when each request occurred and a screenshot of the app after that request so I can associated your action, to a request and a response to a visible result in the app.

**Comment by ruizmarc** [comment]
Closing issue as no feedback was received. Feel free to open a new issue providing the feedback :)
